name: Bump version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION.txt'
  workflow_dispatch:

jobs:
  bump-version:
    if: github.repository == 'KUAILESHANGWEI/LibreTV' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Bump version and commit changes
      run: |
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        echo $(date +"%Y%m%d%H%M") > VERSION.txt
        if git diff --quiet VERSION.txt; then
          echo "VERSION.txt is already current."
          exit 0
        fi
        git add VERSION.txt
        git commit -m "Auto Update $CURRENT_TIME"
        git push origin main
